### ISSUE TITLE
Local files should resize properly on MW 1.39.x

### ISSUE THREAD

**Issue by kghbln** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#59]
**Reference**

 * https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/issues/57

**Setup**
Product | Version
-- | --
MediaWiki | 1.39.3 (8f8ebd1)
PHP | 8.0.29 (apache2handler)
MariaDB | 10.5.17-MariaDB-log
EmbedVideo | 3.2.7 (9e82305)

**Issue**
![Screenshot 2023-06-26 at 16-10-59 File Big Buck Bunny 1080 10s 1MB mp4](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/1104078/0b8963e6-feb9-4ed3-9617-6dec9c48a50e)

This also happens when embedding on pages with  `[[File:Big Buck Bunny 1080 10s 1MB.mp4|800px]]`.

I made sure that no local custom CSS is involved.

I do not know how 1.36 to 1.38 behave. However, they are either EOL or will be EOL very soon.

<hr>

In comparison On 1.35x it works perfectly for `[[File:Big Buck Bunny 1080 10s 1MB.mp4|800px]]`

![grafik](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/1104078/473c9c63-355b-4bc3-8fe1-b29e4a9986ff)

![grafik](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/1104078/00b4541d-a92a-4836-b5ed-dd4c8281fa68)

**Comment by octfx** [comment]
This should be fixed in the develop branch!
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/6594492/a9110336-1be2-4c16-b170-cf5f5b5e7cb1)

**Comment by Brawl345** [comment]
Same problem in MediaWiki 1.35, develop branches fixes it, thanks!

**Comment by keepersdungeon** [comment]
Hello,
I tried the Develop branch but I still have the issue.
Did I miss something?
Thanks

**Comment by octfx** [comment]
Could you try purging the corresponding `File:` page?

**Comment by fuzsin** [comment]
> 

Is missing (unlike the pictures): 
![Originalfile](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/25567074/6204cf5c-5ed9-4d97-959d-926f71400b5c)

**Comment by octfx** [comment]
Can you try purging the page and see if this helps? (i.e. ?action=purge)  
This still seems to be an issue with the FFProbe result (which holds information about dimensions and such) not being retrieved from the cache correctly.

**Comment by fuzsin** [comment]
> 

Already done but without results. I can try to upload a new video file...

**Comment by octfx** [comment]
> Update: unfortunately same problem with new one.
Shoot! I'll put this back on my todo!

**Comment by Tuphal** [comment]
I can also confirm the bug in v1.39.4.

Pictures are shown with resolution:
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/42291781/49972539-2aaf-48e7-a8ab-fa88a259140b)

Videos not:
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/42291781/2d35f6ff-9761-4a6a-ac0a-d5ed3f353a16)

 I also tested the development branch yesterday without success.

**Comment by prodigion** [comment]
While upgrading from 1.39.3 to 1.39.4, I updated EmbedVideo from 3.2.6 to 3.2.7 and it caused this issue.
Reverting back to 3.2.6 fixed the issue.

**Comment by Tuphal** [comment]
I compared both v3.2.6 and v3.2.7 and tested some settings.
When I reversed the change in line 103/104 in `includes/Media/VideoHandler.php` I got it working:
```
$width = 640;
$height = 360;
```
  
When comparing vertical and horizontal videos you can see that in v3.2.6 the videos where resized for the same height:
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/42291781/df72fe42-d844-438b-a110-a5077033ca4e)
   

In v3.2.7 it is resized on the same width (needed to zoom to 50% to fit it):
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/42291781/6a73d647-1712-461f-b87e-a0657048cc33)

I only used `[[File:Modbus TCP WatchdogTimer.mp4|mini|Watchdog viedo]]`

**Comment by Tuphal** [comment]
all mp4 video files doens't have any width/height in the database, thats why the above mentioned if-clause is always TRUE.

![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/42291781/97e73ba4-5e18-4efd-8b51-5542edf2cfaf)

   
I can't figure out how to update these entries.
   
---
The width/height are not updated with the maintenance scripts:

- https://www.mediawiki.org/wiki/Manual:CheckImages.php
`php checkImages.php`
```
Good images: 621/621
``` 
   
- https://www.mediawiki.org/wiki/Manual:RefreshImageMetadata.php
`php refreshImageMetadata.php -mime video/*`
``` 
Finished refreshing file metadata for 7 files. 0 were refreshed, 7 were already up to date, and 0 refreshes were suspicious.
``` 
   
- https://www.mediawiki.org/wiki/Manual:RefreshFileHeaders.php
`php refreshFileHeaders.php --minor_mime mp4`	
``` 
Processing next 7 row(s) starting with Modbus_TCP_WatchdogTimer.mp4.
Updating headers for 7 file(s).
Done. Updated headers for 7 file(s).
```

**Comment by Tuphal** [comment]
one last test from my side. I'm now out. I'm not deep enough in the matter to understand or test anything more. Sorry.
   
Test file resolution according to VLC:
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/42291781/54ba20a2-eaba-4804-874c-d6cb2e39cfc5)

   
I uploaded a new file and set the withdt/height manually:
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/42291781/47d2e7ca-19e2-4742-840c-0c9ccee70b23)
   
On the mediawiki file page I see smaller resolutions:
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/42291781/9940aea0-2ec9-4dc1-b978-8654936b248b)
   
When inserting in a page I still have the wrong resolution:
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/42291781/3ffc71e7-61d9-4a92-b3e7-e2dd53a729d5)
  
This resolution is the if-clause from v3.2.7:
`$height = (int)( $width * ( 16 / 9 ) );`
300px width * (16 / 9) = 533px height

**Comment by octfx** [comment]
So these are actually two separate issues.

The first issue is, that the video metadata isn't correctly retrieved by FFProbe, which results in the filehandler returning 0 for width and height.

This in turn causes the if-clause to run an invalid calculation. To get the correct height the `*` should be a `/`.

I've pushed two commits. The first one refactors the FFProbe logic, and raises the required MW version to 1.37+

The second one fixes the height calculation.

**Comment by fuzsin** [comment]
Just tried it out with the development version (sorry, couldn't format it as code.):

**Internal error:**

[c9e61965368620ee7b049b8c] /index.php/<article> ArgumentCountError: Too few arguments to function MediaWiki\Extension\EmbedVideo\Media\FFProbe\FFProbe::__construct(), 1 passed in <path>/extensions/EmbedVideo/includes/Media/AudioHandler.php on line 297 and exactly 2 expected

Backtrace:

from <path>/extensions/EmbedVideo/includes/Media/FFProbe/FFProbe.php(46)
#0 <path>/extensions/EmbedVideo/includes/Media/AudioHandler.php(297): MediaWiki\Extension\EmbedVideo\Media\FFProbe\FFProbe->__construct()
#1 <path>/extensions/EmbedVideo/includes/Media/AudioHandler.php(253): MediaWiki\Extension\EmbedVideo\Media\AudioHandler->getFFProbeResult()
#2 <path>/extensions/EmbedVideo/includes/Media/VideoHandler.php(100): MediaWiki\Extension\EmbedVideo\Media\AudioHandler->getSizeAndMetadata()
#3 <path>/includes/filerepo/file/File.php(1201): MediaWiki\Extension\EmbedVideo\Media\VideoHandler->normaliseParams()
#4 <path>/includes/linker/Linker.php(469): File->transform()
#5 <path>/includes/parser/Parser.php(5506): MediaWiki\Linker\Linker::makeImageLink()
#6 <path>/includes/parser/Parser.php(2697): Parser->makeImage()
#7 <path>/includes/parser/Parser.php(2441): Parser->handleInternalLinks2()
#8 <path>/includes/parser/Parser.php(1616): Parser->handleInternalLinks()
#9 <path>/includes/parser/Parser.php(700): Parser->internalParse()
#10 <path>/includes/content/WikitextContentHandler.php(346): Parser->parse()
#11 <path>/includes/content/ContentHandler.php(1748): WikitextContentHandler->fillParserOutput()
#12 <path>/includes/content/Renderer/ContentRenderer.php(47): ContentHandler->getParserOutput()
#13 <path>/includes/Revision/RenderedRevision.php(260): MediaWiki\Content\Renderer\ContentRenderer->getParserOutput()
#14 <path>/includes/Revision/RenderedRevision.php(232): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached()
#15 <path>/includes/Revision/RevisionRenderer.php(227): MediaWiki\Revision\RenderedRevision->getSlotParserOutput()
#16 <path>/includes/Revision/RevisionRenderer.php(164): MediaWiki\Revision\RevisionRenderer->combineSlotOutput()
#17 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}()
#18 <path>/includes/Revision/RenderedRevision.php(199): call_user_func()
#19 <path>/includes/poolcounter/PoolWorkArticleView.php(87): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput()
#20 <path>/includes/poolcounter/PoolWorkArticleViewCurrent.php(92): PoolWorkArticleView->renderRevision()
#21 <path>/includes/poolcounter/PoolCounterWork.php(166): PoolWorkArticleViewCurrent->doWork()
#22 <path>/includes/page/ParserOutputAccess.php(299): PoolCounterWork->execute()
#23 <path>/includes/page/Article.php(735): MediaWiki\Page\ParserOutputAccess->getParserOutput()
#24 <path>/includes/page/Article.php(545): Article->generateContentOutput()
#25 <path>/includes/actions/ViewAction.php(78): Article->view()
#26 <path>/includes/MediaWiki.php(556): ViewAction->show()
#27 <path>/includes/MediaWiki.php(333): MediaWiki->performAction()
#28 <path>/includes/MediaWiki.php(923): MediaWiki->performRequest()
#29 <path>/includes/MediaWiki.php(576): MediaWiki->main()
#30 <path>/index.php(50): MediaWiki->run()
#31 <path>/index.php(46): wfIndexMain()
#32 {main}

**Comment by octfx** [comment]
> Just tried it out with the development version (sorry, couldn't format it as code.):
> 
> **Internal error:**
> 
> [c9e61965368620ee7b049b8c] /index.php/
> ArgumentCountError: Too few arguments to function MediaWiki\Extension\EmbedVideo\Media\FFProbe\FFProbe::__construct(), 1 passed in /extensions/EmbedVideo/includes/Media/AudioHandler.php on line 297 and exactly 2 expected

Sorry my mistake, fixed in 50d92e8d1873ca5938d818d9379d34431417b9dd

**Comment by Tuphal** [comment]
The developer branch is working.
Now I have to use `$wgEmbedVideoDefaultWidth` so that the video is not too big on the page. Thats totally acceptable to have a common video size and experience.
Resizing the individual video seems not possible, because of the missing resolution in the file description/database.

With `$wgEmbedVideoDefaultWidth = 320;`:
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/42291781/03cf0896-91db-41a6-9d72-5ec21092f59c)

Without `$wgEmbedVideoDefaultWidth`:
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/42291781/bc3164f3-64ff-42ab-97b4-b6cd2c74bb36)

**Comment by octfx** [comment]
While this now resizes the videos to a common size, the underlying issue still does not seem to be resolved.

1. Are you certain that [`ffmpeg`](https://www.mediawiki.org/wiki/Manual:$wgFFmpegLocation) is installed an callable by the wiki?
2. Does `/usr/bin/ffprobe` exist? If not could you point `$wgFFProbeLocation` to the correct path?
3. Would you be able to disable EmbedVideo (or the local file handler by setting `$wgEmbedVideoEnableVideoHandler=false;`) and check if new uploads still do not contain a width/height?
4. Results from ffprobe are cached indefinitely, you may want to set  `$wgMainCacheType=CACHE_NONE;` while testing.

**Comment by Tuphal** [comment]
ffmpeg is now installed. It was not mentioned as dependency in the description/installation, therefore it was not installed.
Path is correct:
```
which ffmpeg
/usr/bin/ffmpeg
which ffprobe
/usr/bin/ffprobe
``` 

   
   
Now I have width and height in the table for newly uploaded video:
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/42291781/3376a772-3977-412c-bb21-debf824429c1)
   
On the file page I have detailed video information, but an `INVALID Pixel` information:
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/42291781/2a369226-c817-4409-aab5-c60c5edc00e1)
   
When implementing the video on a page with VisualEditor the first try to save the page gets an HTTP error 502, second or third try is working.
   
When resizing the video the size is always a square:
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/42291781/f1cfaa2c-a8d3-4dce-a150-a5b337a2cb76)

   
When deleting the test-video I get following error, but the video is successfully deleted:
```
MediaWiki internal error.

Original exception: [3186e53bf7eb7c3082e4c8db] /w/index.php?title=Datei:test123.mp4&action=delete Error: Call to a member function getDuration() on null
Backtrace:
from /var/www/w/extensions/EmbedVideo/includes/Media/AudioHandler.php(261)
#0 /var/www/w/extensions/EmbedVideo/includes/Media/VideoHandler.php(100): MediaWiki\Extension\EmbedVideo\Media\AudioHandler->getSizeAndMetadata()
#1 /var/www/w/includes/filerepo/file/File.php(1202): MediaWiki\Extension\EmbedVideo\Media\VideoHandler->normaliseParams()
#2 /var/www/w/extensions/PageImages/includes/PageImages.php(277): File->transform()
#3 /var/www/w/includes/HookContainer/HookContainer.php(160): PageImages\PageImages->onBeforePageDisplay()
#4 /var/www/w/includes/HookContainer/HookRunner.php(945): MediaWiki\HookContainer\HookContainer->run()
#5 /var/www/w/includes/OutputPage.php(2871): MediaWiki\HookContainer\HookRunner->onBeforePageDisplay()
#6 /var/www/w/includes/MediaWiki.php(922): OutputPage->output()
#7 /var/www/w/includes/MediaWiki.php(562): MediaWiki->main()
#8 /var/www/w/index.php(50): MediaWiki->run()
#9 /var/www/w/index.php(46): wfIndexMain()
#10 {main}

Exception caught inside exception handler: [3186e53bf7eb7c3082e4c8db] /w/index.php?title=Datei:test123.mp4&action=delete Error: Call to a member function getDuration() on null
Backtrace:
from /var/www/w/extensions/EmbedVideo/includes/Media/AudioHandler.php(261)
#0 /var/www/w/extensions/EmbedVideo/includes/Media/VideoHandler.php(100): MediaWiki\Extension\EmbedVideo\Media\AudioHandler->getSizeAndMetadata()
#1 /var/www/w/includes/filerepo/file/File.php(1202): MediaWiki\Extension\EmbedVideo\Media\VideoHandler->normaliseParams()
#2 /var/www/w/extensions/PageImages/includes/PageImages.php(277): File->transform()
#3 /var/www/w/includes/HookContainer/HookContainer.php(160): PageImages\PageImages->onBeforePageDisplay()
#4 /var/www/w/includes/HookContainer/HookRunner.php(945): MediaWiki\HookContainer\HookContainer->run()
#5 /var/www/w/includes/OutputPage.php(2871): MediaWiki\HookContainer\HookRunner->onBeforePageDisplay()
#6 /var/www/w/includes/exception/MWExceptionRenderer.php(183): OutputPage->output()
#7 /var/www/w/includes/exception/MWExceptionRenderer.php(102): MWExceptionRenderer::reportHTML()
#8 /var/www/w/includes/exception/MWExceptionHandler.php(131): MWExceptionRenderer::output()
#9 /var/www/w/includes/exception/MWExceptionHandler.php(248): MWExceptionHandler::report()
#10 /var/www/w/includes/MediaWiki.php(584): MWExceptionHandler::handleException()
#11 /var/www/w/index.php(50): MediaWiki->run()
#12 /var/www/w/index.php(46): wfIndexMain()
#13 {main}
```

**Comment by Tuphal** [comment]
thank you.
  
One thing I noticed regarding resizing:
When implementing the video in the VisualEditor with default resolution, everything is fine.
When changing the resolution (drag the corners or through Edit-popup), the video is saved as square:
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/42291781/87f3dfca-ab22-4b97-bc9e-da13ede0ae69)

In the source it is saved as:
```
[[Datei:test345.mp4|ohne|mini|default size]]
[[Datei:test345.mp4|ohne|mini|421x421px|resized]]
``` 
   
When changing the dimensions in the source to `[[Datei:test345.mp4|ohne|mini|421px|resized]]` I have the correct video proportions saved:
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/42291781/4148a198-6106-4f16-93c5-bbe52be657be)

**Comment by octfx** [comment]
That's indeed a very weird issue. I can't really pinpoint the origin, but the wikitext VE sends already includes the "square" size. So this _seems_ like it is an issue with VE.

I'll try to investigate, but any help is appreciated.

**Comment by fuzsin** [comment]
> 1. Are you certain that [`ffmpeg`](https://www.mediawiki.org/wiki/Manual:$wgFFmpegLocation) is installed an callable by the wiki?

Nope ) I already suspected it, but I didn't find any info that it is a requirements. 
After the installation everything works as expected: 

![ffmpeg_embedvideo](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/25567074/f3f08fa0-0617-4061-ba2f-8f742d189fad)

Thanks for the great job and fast response!

**Comment by Tuphal** [comment]
Seems as if ffmpeg has one more issue for me...
   
On a **vertical** video, it seems that the width and height are swaped:
   
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/42291781/b392b09f-31fb-449d-a198-13a7bcb3b722)
   
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/42291781/337865e4-d008-4eff-9b70-db931bc801e0)

**Comment by octfx** [comment]
> Seems as if ffmpeg has one more issue for me...
> 
> On a **vertical** video, it seems that the width and height are swaped:
> 
> ![image](https://user-images.githubusercontent.com/42291781/254533414-b392b09f-31fb-449d-a198-13a7bcb3b722.png)
> 
> ![image](https://user-images.githubusercontent.com/42291781/254534180-337865e4-d008-4eff-9b70-db931bc801e0.png)

I've just tested this locally and can't confirm
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/6594492/209b20f7-bc50-4ed1-82bf-07a6a3bd39f4)

Using an example video from https://www.pexels.com/search/videos/vertical/ the renders correctly.

If you want, you can provide me your file so that I can test with this particular example

**Comment by Tuphal** [comment]
Thank you for testing.
I tested it with an video of your link. These are working without issues.

I checked my video files, and it seems that these videos (shot with an iPhone) do not have used the phone rotation correctly, therefore these are switched in the metadata.
I need to check if I can somehow edit the file-metadata or direclty in the mediawiki-DB.

**Comment by mqudsi** [comment]
Hi @octfx, I don't know if you would prefer I open a new issue but I'm still having this problem on the master branch with MediaWiki 1.40.1.

I have `$wgFFmpegLocation` and $wgFFprobeLocation` set in `LocalSettings.php` (they're not the *default* `/usr/bin/{ffmpeg,ffprobe}` and not currently in `$PATH`, for what it's worth). The video gets uploaded but the `img_width` and `img_height` columns in the database are both `0`, and `img_metadata` is null (just `\x`). The rest of the fields in the database appear to be set correctly.

No errors are logged to the PHP error log (`error_log = E_ALL`).

I've confirmed that the php user has permission to execute both those executables, and from the command line I can run `sudo -u <php user> ffmpeg -i /path/to/uploaded/file` and get output that shows that ffmpeg recognizes the video, its codecs, and its resolution:

```
root@palepedia:/opt/palepedia # sudo -u www ffmpeg -hide_banner -i uploads/9/96/video.mp4 
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'uploads/path/to/video.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41iso4
    creation_time   : 2023-11-15T11:37:16.000000Z
  Duration: 00:00:23.71, start: 0.000000, bitrate: 492 kb/s
  Stream #0:0[0x1](und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 480x848, 420 kb/s, 30.04 fps, 30 tbr, 90k tbn (default)
    Metadata:
      creation_time   : 2023-11-15T11:37:16.000000Z
      handler_name    : Vireo Eyes v2.9.1
      vendor_id       : [0][0][0][0]
      encoder         : AVC Coding
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 65 kb/s (default)
    Metadata:
      creation_time   : 2023-11-15T11:37:16.000000Z
      handler_name    : Vireo Ears v2.9.1
      vendor_id       : [0][0][0][0]
At least one output file must be specified
```

**Comment by octfx** [comment]
If the ffmpeg call fails a warning should be generated.

Can you check if the `proc_open` function exists??

**Comment by mqudsi** [comment]
Yes, it's available and I can use it manually to query `ffprobe` against the attachment by loading this script in the browser:

```php
<?php
// Replace this with the path of the file you want to probe
$filepath = '/path/to/media.mp4';
$escapedFilepath = escapeshellarg($filepath);
$cmd = "/usr/local/bin/ffprobe $escapedFilepath";

// Define descriptors for the process to open
$descriptorspec = [
    0 => ["pipe", "r"],
    1 => ["pipe", "w"],
    2 => ["pipe", "w"] 
];

// Open the process using proc_open
$process = proc_open($cmd, $descriptorspec, $pipes, null, null);

if (is_resource($process)) {
    // Close STDIN pipe
    fclose($pipes[0]);

    // Read the outputs
    $stdout = stream_get_contents($pipes[1]);
    $stderr = stream_get_contents($pipes[2]);

    fclose($pipes[1]);
    fclose($pipes[2]);

    // Close the process and get the return value
    $return_value = proc_close($process);

    // Output the results
    echo "STDOUT:\n$stdout\n";
    echo "STDERR:\n$stderr\n";
    echo "Return value: $return_value\n";
} else {
    echo "Failed to open process.";
}
?>
```

giving me

```
STDOUT:

STDERR:
ffprobe version 6.0 Copyright (c) 2007-2023 the FFmpeg developers
  built with FreeBSD clang version 14.0.5 (https://github.com/llvm/llvm-project.git llvmorg-14.0.5-0-gc12386ae247c)
  configuration: --prefix=/usr/local --mandir=/usr/local/man --datadir=/usr/local/share/ffmpeg --docdir=/usr/local/share/doc/ffmpeg --pkgconfigdir=/usr/local/libdata/pkgconfig --disable-static --disable-libcelt --enable-shared --enable-pic --enable-gpl --cc=cc --cxx=c++ --disable-alsa --disable-libopencore-amrnb --disable-libopencore-amrwb --enable-libaom --disable-libaribb24 --enable-asm --enable-libass --disable-libbs2b --disable-libcaca --disable-libcdio --disable-libcodec2 --enable-libdav1d --disable-libdavs2 --disable-libdc1394 --disable-debug --enable-htmlpages --enable-libdrm --disable-libfdk-aac --disable-libflite --enable-fontconfig --enable-libfreetype --enable-frei0r --disable-libfribidi --disable-gcrypt --disable-libglslang --disable-libgme --enable-gmp --enable-gnutls --enable-version3 --disable-libgsm --enable-iconv --disable-libilbc --disable-libjack --enable-libjxl --disable-libklvanc --disable-libkvazaar --disable-ladspa --enable-libmp3lame --enable-lcms2 --disable-liblensfun --disable-libbluray --enable-libplacebo --disable-librsvg --disable-librtmp --enable-libxml2 --disable-lto --disable-lv2 --disable-mbedtls --disable-libmfx --disable-libmodplug --disable-libmysofa --enable-network --disable-nonfree --enable-nvenc --disable-openal --disable-opencl --disable-opengl --disable-libopenh264 --disable-libopenjpeg --disable-libopenmpt --disable-openssl --disable-libopenvino --enable-optimizations --enable-libopus --disable-pocketsphinx --disable-libpulse --disable-librabbitmq --disable-librav1e --disable-librist --enable-runtime-cpudetect --disable-librubberband --disable-sdl2 --enable-libshaderc --disable-libsmbclient --disable-libsnappy --disable-sndio --disable-libsoxr --disable-libspeex --disable-libsrt --disable-libssh --enable-libsvtav1 --disable-libtensorflow --disable-libtesseract --disable-libtheora --disable-libtwolame --disable-libuavs3d --enable-libv4l2 --enable-vaapi --disable-vapoursynth --enable-vdpau --disable-libvidstab --enable-libvmaf --enable-libvorbis --disable-libvo-amrwbenc --disable-libvpl --enable-libvpx --enable-vulkan --enable-libwebp --enable-libx264 --enable-libx265 --disable-libxavs2 --enable-libxcb --disable-libxvid --disable-outdev=xv --disable-libzimg --disable-libzmq --disable-libzvbi
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/path/to/media.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41iso4
    creation_time   : 2023-11-15T11:37:16.000000Z
  Duration: 00:00:23.71, start: 0.000000, bitrate: 492 kb/s
  Stream #0:0[0x1](und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 480x848, 420 kb/s, 30.04 fps, 30 tbr, 90k tbn (default)
    Metadata:
      creation_time   : 2023-11-15T11:37:16.000000Z
      handler_name    : Vireo Eyes v2.9.1
      vendor_id       : [0][0][0][0]
      encoder         : AVC Coding
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 65 kb/s (default)
    Metadata:
      creation_time   : 2023-11-15T11:37:16.000000Z
      handler_name    : Vireo Ears v2.9.1
      vendor_id       : [0][0][0][0]

Return value: 0
```
